config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  resources :users, only: [:new, :create, :show] do
    resources :properties do
      resources :property_elements, only: [:index, :new, :create, :show]
    end
    resources :operations, only: [:new, :create, :index]
  end
  resources :sessions, only: [:create]
  get 'login' => 'sessions#new', :as => :login
  post 'logout' => 'sessions#destroy', :as => :logout
  resources :locations, only: [:new]
  match '/locations/import', to: 'locations#import', via: :post
  #handles properties for non registered users
  #TODO remove default properties resources
  match '/properties/show_all', to: 'properties#show_all', via: :get
  resources :properties do
    match 'visit', via: :get
    match '/property_elements/show_all', via: :get
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_filter :require_login, :only => [:index, :home]

  def home

  end
end

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Real Estate Web</h1>

  <h2>
   El portal donde podrás encontrar el inmueble de tus sueños, o donde simplemente podrás ofrecerlo en venta o alquiler.
  </h2>

  <div class="home_central_image">
  	<%= image_tag "real_estate_home.jpg" %>
  </div>

  <%= link_to "Regístrese !", new_user_path, class: "btn btn-lg btn-primary" %>
  <br/>
  <br/>
  <%= link_to "Buscar Propiedades", properties_show_all_path, class: "btn btn-lg btn-info" %>
</div>