config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  resources :users, only: [:new, :create, :show] do
    resources :properties do
      resources :property_elements, only: [:index, :new, :create, :show]
    end
    resources :operations, only: [:new, :create, :index]
  end
  resources :sessions, only: [:create]
  get 'login' => 'sessions#new', :as => :login
  post 'logout' => 'sessions#destroy', :as => :logout
  resources :locations, only: [:new]
  match '/locations/import', to: 'locations#import', via: :post
  #handles properties for non registered users
  #TODO remove default properties resources
  match '/properties/show_all', to: 'properties#show_all', via: :get
  resources :properties do
    match 'visit', via: :get
    match '/property_elements/show_all', via: :get
  end
end

app/models/property.rb
class Property < ActiveRecord::Base
  include Filterable

  has_many :property_elements, dependent: :destroy

  Cities.data_path = Rails.root.join('config', 'extras', 'cities')

  attr_accessor :city
  attr_accessor :location
  attr_accessor :neighbor

  validates :area, presence: true,
              numericality: true

  validates :floors_number, presence: true,
              numericality: { only_integer: true }

  validates :value, numericality: true
  #TODO set numericality validation without break the spec.
  # validates :value_for_sell, numericality: true
  # validates :value_for_rental, numericality: true

  before_validation(on: [:create, :update]) do
    self.address = full_address
  end

  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  belongs_to :lease_holder

  geocoded_by :address

  reverse_geocoded_by :latitude, :longitude

  after_save :set_is_active

  #TODO add spec coverage for each scope case.
  default_scope { where(is_active: true) }
  scope :located_in, -> (location) { where("address like ?", "%#{location}%") }
  scope :latitude, -> (value) { where("latitude = ?", "#{value}") }
  scope :longitude, -> (value) { where("longitude = ?", "#{value}") }
  #Property.area_greater_than(n).area_lesser_than(m) works like between
  scope :area_greater_than, -> (area) { where("area >= ?", "#{area}") }
  scope :area_lesser_than, -> (area) { where("area <= ?", "#{area}") }
  #Property.for_sell.sell_greater_than(n).sell_lesser_than(m)
  scope :for_sell, -> (value) { where("for_sell = ?", "#{value}") }
  #Property.for_rental.rental_greater_than(n).rental_lesser_than(m)
  scope :value_greater_than, -> (value) { where("value >= ?", "#{value}") }
  scope :value_lesser_than, -> (value) { where("value <= ?", "#{value}") }

  def set_is_active
    self.update_column(:is_active, true)
  end
  private :set_is_active

  def full_address
    if location.nil? || address.present?
      address << ", #{city_and_country}"
    else
      location << ", #{city_and_country}"
    end
  end
  private :full_address

  def city_and_country
    city << ", Colombia" unless city.nil?
  end
  private :city_and_country
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  skip_before_filter :require_login, :only => [:show_all, :visit]

  def index
    @user = LeaseHolder.find(params[:user_id])
    @properties = @user.properties
    if @properties.empty?
      flash[:error] = "No tiene propiedades registradas a la fecha."
      redirect_to user_path(@user.id)
    end
  end

  def new
    @property = Property.new
  end

  def show
    @property = Property.find(params[:id])
  end

  def create
    @property = Property.new(property_params)
    if @property.save
      flash[:success] = 'Propiedad registrada exitosamente.'
      redirect_to user_properties_path(current_user.id)
    else
      flash[:error] = @property.errors.full_messages.join(',')
      render 'new'
    end
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    if @property.update_attributes(property_params)
      flash[:success] = "Propiedad actualizada."
      redirect_to @property
    else
      render 'edit'
    end
  end

  def destroy
    @property = Property.find(params[:id])
    if @property.destroy
      flash[:success] = "Propiedad eliminada."
      redirect_to user_properties_path(current_user)
    else
      render 'show'
    end
  end

  def show_all
    @properties = PropertyPresenter.new(params).filter_properties
    if @properties.empty?
      flash.now[:error] = "No hay propiedades registradas que coincidan con esos criterios de búsqueda."
    end
  end

  def visit
    @property = Property.find(params[:property_id])
  end

  def property_params
    params.require(:property).permit(:city, :value, :neighbor, :location, :address,
                                     :latitude, :longitude, :area, :building_name,
                                     :floors_number, :floor, :for_sell, :lease_holder_id,
                                     :short_description)
  end
end

app/views/properties/index.html.erb
<% provide(:title, @user.username) %>
<section>
  <div class="row">
    <div class="menubar"><%= render_navigation( expand_all: true) %></div>
    <div class="user_info pull-right">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.username %>
      </h1>
    </div>
  </div>
  <div class="row">
    <div class="property_info">
      <h1>Propiedades Registradas</h1>
      <table class="table table-striped">
        <tr>
          <td class="prop_header"># Seq.</td>
          <td class="prop_header">Dirección</td>
          <td class="prop_header">Mapa</td>
        </tr>
        <% @properties.each_with_index do |property, index| %>
          <tr>
            <td>
              <%= index+1 %>
            </td>
            <td>
              <%= link_to "#{property.address}", user_property_path(current_user.id, property.id),title: 'Ver Propiedad', 'data-toggle' => 'tooltip', 'data-placement' => 'right' %>
            </td>
            <% unless property.latitude.nil? && property.longitude.nil? %>
              <td><%= image_tag "http://maps.google.com/maps/api/staticmap?size=200x200&sensor=false&zoom=16&markers=#{property.latitude}%2C#{property.longitude}" %>
              </td>
            <%end%>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</section>

app/views/properties/new.html.erb
<% provide(:title, 'Propiedades::Registrar') %>
<% Cities.data_path = Rails.root.join('config', 'extras', 'cities') %>
<h1>Registrar Propiedad</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
   	<%= form_for @property, url: {action: "create"} do |f| %>
    	<%@countries = CountriesWithCitiesGrouper.new('Americas')%>
    	<%= f.label :city, "Ciudad" %>
      <%= f.select :city, @countries.cities_for('Colombia'),
               { include_blank: true },
               { class: 'chosen-select' } %>

      <%= f.label :neighbor, "Barrio:" %>
      <%= f.text_field :neighbor %>

      <%= f.label :location, "Dirección:" %>
      <%= f.text_field :location %>

      <%= f.label :area, "Área del Inmueble*:" %>
      <%= f.text_field :area %>

      <%= f.label :building_name, "Urbanización:" %>
      <%= f.text_field :building_name %>

      <%= f.label :floors_number, "# Pisos:" %>
      <%= f.number_field :floors_number %>

			<%= f.label :floors, "Piso:" %>
      <%= f.number_field :floor %>

      <%= f.label :op_rental, "Arrendar/Rentar"%>
      <%= f.radio_button :for_sell, "0", required: true %>

      <%= f.label :op_sell, "Vender" %>
      <%= f.radio_button :for_sell, "1", required: true %>

			<%= f.label :value, "Valor:" %>
      <%= f.number_field :value %>

      <%= f.hidden_field :lease_holder_id, value: current_user.id %>

      <%= f.submit "Registrar", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/properties/show.html.erb
<% provide(:title, "Mi Propiedad") %>
<section>
  <div class="row">
		<div class="menubar"><%= render_navigation( expand_all: true) %></div>
		<div class="user_info pull-right">
  		<h1>
        Detalles de la Propiedad
  		</h1>
		</div>
  </div>
  <div class="row">
	  <aside class="col-md-4">
      <div id="property_address">
        <h3> Dirección: </h3>
        <%= @property.address %>
      </div>
      <div id="property_floor">
        <h3> Piso: </h3>
        <%= @property.floor %>
      </div>
      <div id="property_value">
        <h3> Valor: </h3>
        <%= @property.value %>
      </div>
      <div id="property_area">
        <h3> Area: </h3>
        <%= @property.area %> m2
      </div>
      <% if @property.building_name.present? %>
        <div id="property_building_name">
          <h3> Edificio: </h3>
          <%= @property.building_name %>
        </div>
      <% end %>
      <div id="property_nearby_loc">
        <h3> Lugares Cercanos: </h3>
        <% @locations = Location.near([@property.latitude, @property.longitude], 2, units: :km) %>
        <table class="table table-striped">
          <tr>
            <td class="prop_header">Dirección</td>
            <td class="prop_header">Descripción</td>
            <td class="prop_header">Distancia</td>
          </tr>
          <% @locations.each do |location|%>
            <tr>
              <td><%= location.address %></td>
              <td><%= location.description %></td>
              <td><%= location.distance.round(2) %> Km</td>
            </tr>
          <% end %>
        </table>
      </div>
	  </aside>
    <aside class="col-md-4">
      <div id="property_map">
        <h3> Mapa: </h3>
        <%= image_tag "http://maps.google.com/maps/api/staticmap?size=300x200&sensor=true&zoom=16&markers=#{@property.latitude}%2C#{@property.longitude}" %>
      </div>
    </aside>
    <aside class="col-md-3">
      <div id="config_property_elements">
        <%= link_to user_property_property_elements_path(current_user.id, @property.id), class: "btn btn-default" do %>
          <i class="glyphicon glyphicon-wrench"> Configuración </i>
        <% end %>
      </div>
      <br/>
      <div id="property_opts_edit">
        <%= link_to edit_user_property_path(current_user, @property), class: "btn btn-default" do %>
          <i class="glyphicon glyphicon-edit"> Editar</i>
        <% end %>
      </div>
      <br/>
      <div id="property_opts_drop">
        <%= link_to user_property_path(current_user.id, @property.id), method: :delete, class: "btn btn-default", data: {confirm: "Desea borrar esta propiedad ?"} do %>
          <i class="glyphicon glyphicon-remove"> Eliminar </i>
        <% end %>
      </div>
      <div id="property_elements_prev">
        <% @elements_presenter = PropertyElementPresenter.new(@property.id) %>
        <% ElementType.all.each do |type| %>
          </br>
          <span class="<%= @elements_presenter.glyphicon_for_type(type.name) %>" ></span> <%= type.name %>: <%= @elements_presenter.types_for_property[type.name] %>
        <% end %>
      </div>
    </aside>
  </div>
</section>

app/views/properties/show_all.html.erb
<section>
  <div class="row">
    <h1>Propiedades Disponibles</h1>
    </br>
    <div class="row">
      <div class="col-md-3">
        <%= form_tag properties_show_all_path, method: 'get', class: 'well form-search' do %>
          <p>
          <div id="filter_options" class="prop_filter_by_map_button">
            <h4> Activar Mapa </h4>
          </div>
          <p>
          <div id="filter_options" class="prop_filter_button">
            <h4> Activar Formulario </h4>
          </div>
          <p>
          <div id="prop_filter_by_map" class="hidden">
            <h4>Click sobre el mapa para activarlo</h4>
            <h4>Seleccione un punto en el mapa donde desea buscar.</h4>
            <%= render_gmap_coordinate_picker %>
          </div>
          <hr>
          <div id="prop_filter" class="hidden">
            <h4>Defina los criterios de Búsqueda</h4>
            <%= label_tag :for_rental, "Arriendo:", required: true %>
            <%= radio_button_tag :for_sell, '0' %>
            <%= label_tag :for_sell, "Venta:" %>
            <%= radio_button_tag :for_sell, '1', required: true %>
            <h4>Ubicación</h4>
            <%= text_field_tag :located_in, nil, class: 'input-small' %>
            <h4>Area</h4>
            <%= label_tag :area_from, "desde:" %>
            <%= number_field_tag :area_greater_than, 0, class: 'input-small' %>
            <%= label_tag :area_to, "hasta:" %>
            <%= number_field_tag :area_lesser_than, 0, class: 'input-small' %>
            <h4>Precio</h4>
            <%= label_tag :area_from, "desde:" %>
            <%= number_field_tag :value_greater_than, 0, class: 'input-small' %>
            <%= label_tag :area_to, "hasta:" %>
            <%= number_field_tag :value_lesser_than, 0, class: 'input-small' %>
          </div>
            <hr>
          <%= submit_tag "Buscar" %>
          </p>
        <% end %>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <div class="property_info">
          <table class="table table-striped">
            <tr>
              <td class="prop_header"># Seq.</td>
              <td class="prop_header">Dirección</td>
              <td class="prop_header">Mapa</td>
            </tr>
            <% @properties.each_with_index do |property, index| %>
              <tr>
                <td>
                  <%= index+1 %>
                </td>
                <td>
                  <%= link_to "#{property.address}", property_visit_path(property.id),title: 'Ver Propiedad', 'data-toggle' => 'tooltip', 'data-placement' => 'right' %>
                </td>
                <% unless property.latitude.nil? && property.longitude.nil? %>
                  <td><%= image_tag "http://maps.google.com/maps/api/staticmap?size=200x200&sensor=false&zoom=16&markers=#{property.latitude}%2C#{property.longitude}" %>
                  </td>
                <%end%>
              </tr>
            <% end %>
          </table>
        </div>
        <%= will_paginate @properties %>
      </div>
    </div>
    </br>
  </div>
</section>

app/views/properties/visit.html.erb
<section>
  <div class="row">
	  <aside class="col-md-4">
      <div id="property_address">
        <h3> Dirección: </h3>
        <%= @property.address %>
      </div>
      <div id="property_floor">
        <h3> Piso: </h3>
        <%= @property.floor %>
      </div>
      <div id="property_value">
        <h3> Valor: </h3>
        <% if @property.value_for_sell.present? %>
          <%= @property.value_for_sell %>
        <% elsif @property.value_for_rental.present? %>
          <%= @property.value_for_rental %>
        <%end%>
      </div>
      <div id="property_area">
        <h3> Area: </h3>
        <%= @property.area %> m2
      </div>
      <% if @property.building_name.present? %>
        <div id="property_building_name">
          <h3> Edificio: </h3>
          <%= @property.building_name %>
        </div>
      <% end %>
      <div id="property_nearby_loc">
        <h3> Lugares Cercanos: </h3>
        <% @locations = Location.near([@property.latitude, @property.longitude], 2, units: :km) %>
        <table class="table table-striped">
          <tr>
            <td class="prop_header">Dirección</td>
            <td class="prop_header">Descripción</td>
            <td class="prop_header">Distancia</td>
          </tr>
          <% @locations.each do |location|%>
            <tr>
              <td><%= location.address %></td>
              <td><%= location.description %></td>
              <td><%= location.distance.round(2) %> Km</td>
            </tr>
          <% end %>
        </table>
      </div>
      </br>
      </br>
      <%= link_to properties_show_all_path , class: "btn btn-primary" do %>
        <i class="glyphicon glyphicon-chevron-left">Regresar</i>
      <% end %>
	  </aside>
    <aside class="col-md-4">
      <div id="property_map">
        <h3> Mapa: </h3>
        <%= image_tag "http://maps.google.com/maps/api/staticmap?size=300x200&sensor=true&zoom=16&markers=#{@property.latitude}%2C#{@property.longitude}" %>
      </div>
    </aside>
    <aside class="col-md-3">
      <div id="config_property_elements">
        <%= link_to property_property_elements_show_all_path(@property.id), class: "btn btn-info" do %>
          <i class="glyphicon glyphicon-ok-sign">Detalles</i>
        <% end %>
        </br>
        </br>
        <%= link_to '#', class: "btn btn-default" do %>
          <i class="glyphicon glyphicon-screenshot">Ofertar</i>
        <% end %>
        </br>
        </br>
        <%= link_to '#', class: "btn btn-default" do %>
          <i class="glyphicon glyphicon-star">Calificar</i>
        <% end %>
        </br>
        </br>
        <%= link_to '#', class: "btn btn-default" do %>
          <i class="glyphicon glyphicon-hand-right">Comentar</i>
        <% end %>
        </br>
        </br>
      </div>
      <div id="property_elements_prev">
        <% @elements_presenter = PropertyElementPresenter.new(@property.id) %>
        <% ElementType.all.each do |type| %>
          </br>
          <span class="<%= @elements_presenter.glyphicon_for_type(type.name) %>" ></span> <%= type.name %>: <%= @elements_presenter.types_for_property[type.name] %>
        <% end %>
      </div>
    </aside>
  </div>
</section>