config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  resources :users, only: [:new, :create, :show] do
    resources :properties do
      resources :property_elements, only: [:index, :new, :create, :show]
    end
    resources :operations, only: [:new, :create, :index]
  end
  resources :sessions, only: [:create]
  get 'login' => 'sessions#new', :as => :login
  post 'logout' => 'sessions#destroy', :as => :logout
  resources :locations, only: [:new]
  match '/locations/import', to: 'locations#import', via: :post
  #handles properties for non registered users
  #TODO remove default properties resources
  match '/properties/show_all', to: 'properties#show_all', via: :get
  resources :properties do
    match 'visit', via: :get
    match '/property_elements/show_all', via: :get
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Síganos en <a href="https://twitter.com/?lang=es">Twitter</a>
    y <a href="https://www.facebook.com/">Facebook</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Acerca De",   '#' %></li>
      <li><%= link_to "Contáctenos", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Real Estate Web", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   '#' %></li>
        <% if current_user %>
          <li>Logged in as <%= link_to "#{current_user.email}", user_path(current_user.id) %></li>
        <%else%>
          <li><%= link_to "iniciar sesión", :login %></li>
        <%end%>
        <% if current_user %>
        <li><%= link_to "salir", :logout, method: :post %></li>
        <%end%>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Real State Web Home Page</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render partial: "layouts/flash_messages", flash: flash %>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>